services:
  db:
    image: docker.io/postgres:16.4-alpine3.20
    environment:
      POSTGRES_DB: paraia_dev
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - paraia_dev_data:/var/lib/postgresql/data
volumes:
  paraia_dev_data:
